on: [push]
name: Acid CI
jobs:
  build_and_test:
    name: Acid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: example
          
      - name: Compile the Acid site.
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- -b site
      - name: Scaffold a new Acid site.
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- -n some_site
      - name: Scaffold a new Acid theme.
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- -t some_theme
      - name: Get Acid version info.
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- -h
      - name: Get Acid version info.
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- -v
      - name: Checking.
        run: tree site/build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: site/build
